[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bairds_counterexample_env"
version = "0.0.1"
dependencies = [
  "numpy",
  "gymnasium"
]

[tool.setuptools]
packages = ["bairds_counterexample_env"]